blank_issues_enabled: false
contact_links:
  - name: Twitter
    url: https://twitter.com/seeu_inspace
    about: Please contact me here or on LinkedIn.
  - name: LinkedIn
    url: https://www.linkedin.com/in/riccardo-malatesta"/>nnn
    about: Please contact me here or on Twitter.
